# Generated by Django 4.2.1 on 2023-05-24 06:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    replaces = [
        ("navigation", "0001_initial"),
        ("navigation", "0002_auto_20220426_0835"),
        ("navigation", "0003_alter_navigationmenusetting_items"),
        ("navigation", "0004_alter_navigationmenusetting_items"),
        ("navigation", "0005_rename_items_navigationmenusetting_menu_items"),
        ("navigation", "0006_alter_navigationmenusetting_menu_items"),
    ]

    initial = True

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationMenuSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_items",
                    wagtail.fields.StreamField(
                        [
                            (
                                "internal_page",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock()),
                                        ("page", wagtail.blocks.PageChooserBlock()),
                                        (
                                            "anchor",
                                            wagtail.blocks.CharBlock(
                                                help_text="For linking to specific page elements. Enter the anchor text without the leading '#' symbol.",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "external_link",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock()),
                                        ("url", wagtail.blocks.URLBlock()),
                                        (
                                            "anchor",
                                            wagtail.blocks.CharBlock(
                                                help_text="For linking to specific page elements. Enter the anchor text without the leading '#' symbol.",
                                                required=False,
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "drop_down",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock()),
                                        (
                                            "menu_items",
                                            wagtail.blocks.StreamBlock(
                                                [
                                                    (
                                                        "page",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(),
                                                                ),
                                                                (
                                                                    "page",
                                                                    wagtail.blocks.PageChooserBlock(),
                                                                ),
                                                                (
                                                                    "anchor",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="For linking to specific page elements. Enter the anchor text without the leading '#' symbol.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                    (
                                                        "external_link",
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                (
                                                                    "title",
                                                                    wagtail.blocks.CharBlock(),
                                                                ),
                                                                (
                                                                    "url",
                                                                    wagtail.blocks.URLBlock(),
                                                                ),
                                                                (
                                                                    "anchor",
                                                                    wagtail.blocks.CharBlock(
                                                                        help_text="For linking to specific page elements. Enter the anchor text without the leading '#' symbol.",
                                                                        required=False,
                                                                    ),
                                                                ),
                                                            ]
                                                        ),
                                                    ),
                                                ]
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation menu",
            },
        ),
    ]
