# Generated by Django 4.1.7 on 2023-02-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0004_alter_navigationmenusetting_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="navigationmenusetting",
            old_name="items",
            new_name="menu_items",
        ),
    ]
