# Generated by Django 2.2.1 on 2019-06-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
    ]
