# Generated by Django 3.2.8 on 2021-11-03 17:08

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='US/Pacific'),
        ),
    ]
