# Generated by Django 3.2.8 on 2021-11-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='teaser',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
