# Generated by Django 3.2.12 on 2022-03-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='teaser',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
