# Generated by Django 4.2.1 on 2023-06-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_squashed_0018_eventsponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="drupal_body_migrated",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="drupal_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
