# Generated by Django 5.1 on 2024-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0023_alter_event_body"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["start_date"], name="events_start_d_6c01fc_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["end_date"], name="events_end_dat_f7b00b_idx"),
        ),
    ]
