# Generated by Django 6.1.1 on 2026-09-26 20:39

from django.db import migrations


# Columns that are becoming NOT NULL, keyed by model name.
NULLABLE_FIELDS = {"event": ["teaser", "website"]}

# Page revisions store field values as JSON, so old revisions and unpublished
# drafts would fail to save once the columns are NOT NULL. Keys are page model
# names; "" holds the page's own fields and other keys name child relations.
REVISION_FIELDS = {"event": {"": ["teaser", "website"]}}


def blank_nulls(data, fields):
    changed = False
    for field in fields:
        if field in data and data[field] is None:
            data[field] = ""
            changed = True
    return changed


def replace_nulls_with_empty_strings(apps, schema_editor):
    for model_name, fields in NULLABLE_FIELDS.items():
        model = apps.get_model("events", model_name)
        for field in fields:
            model.objects.filter(**{f"{field}__isnull": True}).update(**{field: ""})

    Revision = apps.get_model("wagtailcore", "Revision")
    for model_name, groups in REVISION_FIELDS.items():
        revisions = Revision.objects.filter(
            content_type__app_label="events",
            content_type__model=model_name,
        )
        for revision in revisions.iterator():
            changed = False
            for relation, fields in groups.items():
                if relation:
                    items = revision.content.get(relation) or []
                else:
                    items = [revision.content]
                for item in items:
                    changed = blank_nulls(item, fields) or changed
            if changed:
                revision.save(update_fields=["content"])


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("events", "0025_alter_event_body"),
    ]

    operations = [
        migrations.RunPython(
            replace_nulls_with_empty_strings,
            migrations.RunPython.noop,
        ),
    ]
