# Generated by Django 6.1.1 on 2026-09-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0026_replace_null_strings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="drupal_body_migrated",
        ),
        migrations.RemoveField(
            model_name="event",
            name="drupal_path",
        ),
        migrations.AlterField(
            model_name="event",
            name="teaser",
            field=models.TextField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="website",
            field=models.URLField(blank=True, default="", max_length=300),
        ),
    ]
