# Generated by Django 6.1.1 on 2026-10-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_drop_drupal_fields_non_nullable_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='open_in_new_tab',
            field=models.BooleanField(default=True, help_text='Open the event website link in a new browser tab. Turn this off for links that should stay in the same tab, such as links to pages on this site.', verbose_name='Open website link in a new tab'),
        ),
    ]
