# Generated by Django 4.2.5 on 2023-11-05 09:46

from django.db import migrations, models
import wagtail.contrib.forms.models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0001_squashed_0002_alter_formfield_choices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactformpage",
            name="from_address",
            field=models.EmailField(
                blank=True, max_length=255, verbose_name="from address"
            ),
        ),
        migrations.AddField(
            model_name="contactformpage",
            name="subject",
            field=models.CharField(blank=True, max_length=255, verbose_name="subject"),
        ),
        migrations.AddField(
            model_name="contactformpage",
            name="to_address",
            field=models.CharField(
                blank=True,
                help_text="Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.",
                max_length=255,
                validators=[wagtail.contrib.forms.models.validate_to_address],
                verbose_name="to address",
            ),
        ),
    ]
