# Generated by Django 5.0.7 on 2024-07-31 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0003_contactformpage_from_address_contactformpage_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formfield",
            name="page",
        ),
        migrations.DeleteModel(
            name="ContactFormPage",
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
    ]
