# Generated by Django 4.2.2 on 2023-07-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="drupal_body_migrated",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="drupal_node_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="drupal_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
