# Generated by Django 4.2.4 on 2023-08-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_drupal_body_migrated_product_drupal_node_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
