# Generated by Django 4.2.4 on 2023-08-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_product_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
