# Generated by Django 4.2.4 on 2023-08-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_alter_product_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
