# Generated by Django 4.2.5 on 2023-10-07 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_alter_product_is_featured"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="price_usd",
        ),
    ]
