# Generated by Django 6.1.1 on 2026-09-26 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_rename_price_product_price_usd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="drupal_body_migrated",
        ),
        migrations.RemoveField(
            model_name="product",
            name="drupal_path",
        ),
    ]
