# Generated by Django 3.2.10 on 2021-12-08 16:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newstopic_newstopicsindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstopic',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
