# Generated by Django 3.2.11 on 2022-01-12 11:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_alter_bookauthor_id'),
        ('magazine', '0038_alter_magazinearticle_body'),
        ('library', '0009_auto_20210513_0642'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailmenus', '0024_auto_20211013_1742'),
        ('news', '0004_newstype_newstypeindexpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsTopicsIndexPage',
            new_name='NewsTopicIndexPage',
        ),
    ]
