# Generated by Django 3.2.11 on 2022-01-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='teaser',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
