# Generated by Django 3.2.11 on 2022-01-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsitem_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='teaser',
            field=models.TextField(help_text='Briefly summarize the news item for display in news lists', max_length=100, null=True),
        ),
    ]
