# Generated by Django 4.2.7 on 2023-12-20 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("facets", "0001_initial"),
        ("news", "0027_newsitemtopic_remove_newstopicindexpage_page_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newstypeindexpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="newsitem",
            name="news_type",
        ),
        migrations.AddField(
            model_name="newsitem",
            name="news_genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="facets.genre",
            ),
        ),
        migrations.DeleteModel(
            name="NewsType",
        ),
        migrations.DeleteModel(
            name="NewsTypeIndexPage",
        ),
    ]
