# Generated by Django 4.2.7 on 2023-12-20 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0028_remove_newstypeindexpage_page_ptr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsitem",
            name="news_genre",
        ),
    ]
