# Generated by Django 6.1.1 on 2026-09-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0031_replace_null_strings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsitem",
            name="body_migrated",
        ),
        migrations.RemoveField(
            model_name="newsitem",
            name="drupal_body_migrated",
        ),
        migrations.RemoveField(
            model_name="newsitem",
            name="drupal_path",
        ),
        migrations.AlterField(
            model_name="newsitem",
            name="teaser",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Briefly summarize the news item for display in news lists",
                max_length=100,
            ),
        ),
    ]
