# Generated by Django 2.1.7 on 2019-04-02 18:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magazine', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeaturedarticle',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='magazine.MagazineArticle'),
        ),
        migrations.AddField(
            model_name='homepagefeaturedarticle',
            name='home_page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_articles', to='home.HomePage'),
        ),
    ]
