# Generated by Django 2.1.3 on 2018-11-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagefeaturedarticle'),
    ]

    operations = [
        migrations.RenameField('HomePage', 'body', 'intro'),
    ]
