# Generated by Django 2.2.4 on 2019-11-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(choices=[(1, 'One year'), (2, 'Two years ($10 discount)'), (3, 'Three years ($20 discount)')], default=1, help_text='Number of years this subscription is active.'),
            preserve_default=False,
        ),
    ]
