# Generated by Django 2.2.4 on 2019-11-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='shipping_cost',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(choices=[(1, 'One year'), (2, 'Two years ($10 discount)'), (3, 'Three years ($25 discount)')], help_text='Number of years this subscription is active.'),
        ),
    ]
