# Generated by Django 2.2.4 on 2019-11-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20191103_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber_address_country',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber_address_locality',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber_address_region',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber_po_box_number',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber_postal_code',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber_street_address',
        ),
    ]
