# Generated by Django 2.2.4 on 2019-11-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('subscription', '0004_auto_20191113_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscriber_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address'),
        ),
    ]
