# Generated by Django 2.2.4 on 2019-11-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscription_subscriber_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address'),
        ),
    ]
