# Generated by Django 2.2.4 on 2019-12-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20191122_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='braintree_id',
            field=models.CharField(blank=True, help_text='DO NOT EDIT. Used to cross-reference subscriptions with Braintree payments.', max_length=255),
        ),
    ]
