# Generated by Django 4.2.4 on 2023-08-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0005_alter_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="price_group",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("true_cost", "True cost"),
                    ("low_income", "Low income"),
                    ("international", "International"),
                ],
                default="basic",
                max_length=255,
            ),
        ),
    ]
