# Generated by Django 4.2.5 on 2023-10-12 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0006_alter_subscription_price_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="braintree_subscription_id",
        ),
    ]
