# Generated by Django 4.2.5 on 2023-10-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0008_subscription_paypal_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="paypal_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255, unique=True),
        ),
    ]
