# Generated by Django 2.2.4 on 2019-12-11 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_auto_20191210_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber_email',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='subscriber email'),
        ),
    ]
