# Generated by Django 2.2.4 on 2019-12-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_auto_20191211_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscriber_po_box_number',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber_street_address_line_2',
            field=models.CharField(blank=True, default='', help_text='If needed, second line for mailing address.', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_address_locality',
            field=models.CharField(blank=True, help_text='City for the mailing address.', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_address_region',
            field=models.CharField(blank=True, default='', help_text='State for the mailing address.', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_family_name',
            field=models.CharField(default='', help_text='Enter the family (last) name for the subscriber.', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_given_name',
            field=models.CharField(default='', help_text='Enter the given (first) name for the subscriber.', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_postal_code',
            field=models.CharField(blank=True, help_text='Postal code for the mailing address.', max_length=16),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_street_address',
            field=models.CharField(blank=True, default='', help_text='The street address where this subscription should be mailed.', max_length=255),
        ),
    ]
