# Generated by Django 4.2.5 on 2023-10-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0009_alter_subscription_paypal_subscription_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["paypal_subscription_id"], name="subscriptio_paypal__0e9eb0_idx"
            ),
        ),
    ]
