# Generated by Django 2.2.8 on 2019-12-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_auto_20191211_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_address_country',
            field=models.CharField(blank=True, default='United States', help_text='Country for mailing.', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_street_address',
            field=models.CharField(blank=True, default='', help_text='The street address where a print subscription could be mailed.', max_length=255),
        ),
    ]
