# Generated by Django 4.2.5 on 2023-10-14 08:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0011_remove_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "paypal_button",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "paypal_plan_id",
                                    wagtail.blocks.CharBlock(required=True),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
