# Generated by Django 3.0.7 on 2020-07-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_auto_20191221_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(1, 'One year'), (2, 'Two years ($10 discount)'), (3, 'Three years ($25 discount)')], help_text='Number of years this subscription is active.', null=True),
        ),
    ]
