# Generated by Django 4.2.5 on 2023-10-14 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscription", "0012_subscriptionindexpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                unique=True,
                verbose_name="subscriber",
            ),
        ),
    ]
