# Generated by Django 3.0.7 on 2020-07-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_auto_20200721_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='duration',
        ),
    ]
