# Generated by Django 4.2.5 on 2023-10-14 22:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0013_alter_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionindexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "paypal_button",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "paypal_plan_id",
                                    wagtail.blocks.CharBlock(required=True),
                                ),
                                (
                                    "paypal_plan_name",
                                    wagtail.blocks.CharBlock(required=True),
                                ),
                                (
                                    "paypal_plan_price",
                                    wagtail.blocks.IntegerBlock(required=True),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
