# Generated by Django 3.0.7 on 2020-07-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_subscription_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='recurring',
            field=models.BooleanField(default=True),
        ),
    ]
