# Generated by Django 3.0.7 on 2020-07-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_auto_20200721_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='braintree_id',
            new_name='braintree_subscription_id',
        ),
    ]
