# Generated by Django 4.2.5 on 2023-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0017_alter_subscriptionindexpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                help_text="The date the subscription expires. Leave blank for perpetual subscriptions.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="paypal_subscription_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The PayPal subscription ID. If this field has a value, PayPal will manage the expiration date.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
