# Generated by Django 4.2.6 on 2023-10-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0018_subscription_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="paypal_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="The PayPal subscription ID. If this field has a value, PayPal will manage the expiration date.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
