# Generated by Django 3.1.1 on 2020-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0020_auto_20201129_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price_group',
            field=models.CharField(choices=[('normal', 'Normal'), ('true_cost', 'True cost'), ('low_income', 'Low income'), ('international', 'International')], default='normal', max_length=255),
        ),
    ]
