# Generated by Django 3.1.1 on 2020-11-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0021_subscription_price_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
