# Generated by Django 3.1.1 on 2021-01-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0022_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscriber_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
