# Generated by Django 6.1.1 on 2026-09-27 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerPolicySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_search', models.BooleanField(default=True, help_text='Allow search engines to index pages and link to them.', verbose_name='Search engines')),
                ('allow_ai_input', models.BooleanField(default=True, help_text='Allow AI systems to read pages to answer questions, for example in AI search results and chat assistants.', verbose_name='AI answers')),
                ('allow_ai_train', models.BooleanField(default=True, help_text='Allow AI systems to learn from pages when building AI models.', verbose_name='AI training')),
                ('publish_llms_txt', models.BooleanField(default=True, help_text='Publish a guide to the site for AI systems at /llms.txt, built from the navigation menu.', verbose_name='Publish llms.txt')),
                ('llms_txt_summary', models.TextField(blank=True, default='Western Friend is a Quaker nonprofit that publishes a magazine, books, and other resources exploring the spiritual lives of Friends (Quakers) in the western United States and beyond.', help_text='One paragraph describing the site, shown at the top of llms.txt.', verbose_name='Site summary')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Crawlers and AI',
            },
        ),
    ]
