# Generated by Django 3.2.13 on 2022-04-27 18:18

import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.images.blocks
from django.db import migrations

import blocks.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("magazine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazinearticle",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("document", wagtail.documents.blocks.DocumentChooserBlock()),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "width",
                                    wagtail.blocks.IntegerBlock(
                                        help_text="Enter the desired image width value in pixels up to 800 max.",
                                        max_value=800,
                                        min_value=0,
                                    ),
                                ),
                            ],
                            classname="full title",
                        ),
                    ),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "superscript",
                                "superscript",
                                "strikethrough",
                                "blockquote",
                            ]
                        ),
                    ),
                    ("pullquote", blocks.blocks.PullQuoteBlock()),
                ]
            ),
        ),
    ]
