# Generated by Django 4.1.2 on 2022-10-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magazine", "0012_alter_magazinearticle_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazinearticle",
            name="drupal_node_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
