# Generated by Django 4.1.6 on 2023-02-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magazine", "0018_alter_magazinearticle_body"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="archiveissue",
            index=models.Index(
                fields=["internet_archive_identifier"],
                name="magazine_ar_interne_78a924_idx",
            ),
        ),
    ]
