# Generated by Django 4.1.6 on 2023-02-12 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("magazine", "0021_alter_archivearticleauthor_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivearticleauthor",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_articles_authored",
                to="wagtailcore.page",
            ),
        ),
    ]
