# Generated by Django 4.1.8 on 2023-05-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magazine", "0022_alter_archivearticleauthor_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="magazineissue",
            name="drupal_node_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
