# Generated by Django 4.1.7 on 2023-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0015_alter_newsitem_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="body_migrated",
            field=models.TextField(
                blank=True,
                help_text="Used only for content from old Drupal website.",
                null=True,
            ),
        ),
    ]
