# Generated by Django 4.1.7 on 2023-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0016_newsitem_body_migrated"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="drupal_node_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
