# Generated by Django 2.2.9 on 2020-02-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationindexpage',
            name='body',
        ),
    ]
