# Generated by Django 2.1.7 on 2019-05-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['title']},
        ),
    ]
