# Generated by Django 3.0.5 on 2020-04-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200421_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.CharField(blank=True, default='', help_text='Enter the given name for a person.', max_length=255, null=True),
        ),
    ]
