# Generated by Django 3.1 on 2020-09-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20200422_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='civicrm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
