# Generated by Django 2.1.7 on 2019-05-21 18:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_organizationindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationindexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('organizations', wagtail.core.blocks.StructBlock([]))], null=True),
        ),
    ]
