# Generated by Django 3.1.1 on 2020-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_meeting_civicrm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='civicrm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
