# Generated by Django 4.2.1 on 2023-06-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_squashed_0007_person_person_civicrm_9c9d2e_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingaddress",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
