# Generated by Django 4.2.5 on 2023-09-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0008_alter_meetingaddress_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="information_last_verified",
            field=models.DateField(blank=True, null=True),
        ),
    ]
