# Generated by Django 3.1.1 on 2020-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_organization_civicrm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
