# Generated by Django 2.2.1 on 2019-05-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_personindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingindexpage',
            name='body',
        ),
    ]
