# Generated by Django 3.1.1 on 2020-09-30 15:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20200922_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('street_address', models.CharField(blank=True, default='', max_length=255)),
                ('extended_address', models.CharField(blank=True, default='', max_length=255)),
                ('po_box_number', models.CharField(blank=True, default='', help_text='P.O. Box, if relevant.', max_length=32)),
                ('locality', models.CharField(help_text='City for the shipping address.', max_length=255)),
                ('region', models.CharField(blank=True, default='', help_text='State or region.', max_length=255)),
                ('postal_code', models.CharField(help_text='Postal code (or zipcode).', max_length=16)),
                ('country', models.CharField(default='United States', help_text='Country for shipping.', max_length=255)),
                ('address_type', models.CharField(choices=[('mailing', 'mailing'), ('worship', 'worship')], max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contact.meeting')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
