# Generated by Django 5.1.7 on 2025-03-28 10:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0009_meeting_information_last_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for this contact",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number for this contact",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for this contact",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number for this contact",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="website",
            field=models.URLField(
                blank=True, help_text="Website URL for this contact", null=True
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="civicrm_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID in the CiviCRM system",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="drupal_author_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID of the author in Drupal",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="drupal_duplicate_author_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                help_text="IDs of duplicate authors in Drupal",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="drupal_library_author_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID of the library author in Drupal",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for this contact",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number for this contact",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="website",
            field=models.URLField(
                blank=True, help_text="Website URL for this contact", null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="civicrm_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID in the CiviCRM system",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="drupal_author_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID of the author in Drupal",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="drupal_duplicate_author_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                help_text="IDs of duplicate authors in Drupal",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="drupal_library_author_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID of the library author in Drupal",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website",
            field=models.URLField(
                blank=True, help_text="Website URL for this contact", null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="civicrm_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID in the CiviCRM system",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="drupal_author_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID of the author in Drupal",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="drupal_duplicate_author_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                help_text="IDs of duplicate authors in Drupal",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="drupal_library_author_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="ID of the library author in Drupal",
                null=True,
            ),
        ),
    ]
