# Generated by Django 3.1.1 on 2020-09-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_meetingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingaddress',
            name='address_type',
            field=models.CharField(choices=[('mailing', 'Mailing'), ('worship', 'Worship')], max_length=255),
        ),
    ]
