# Generated by Django 5.1.7 on 2025-03-29 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0010_organization_email_organization_phone_person_email_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPublicationStatistics",
            fields=[
                (
                    "contact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="publication_statistics",
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("meeting", "Meeting"),
                            ("organization", "Organization"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("article_count", models.PositiveIntegerField(default=0)),
                ("last_published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Publication Statistics",
                "verbose_name_plural": "Contact Publication Statistics",
                "indexes": [
                    models.Index(
                        fields=["contact_type"], name="contact_con_contact_5ef721_idx"
                    ),
                    models.Index(
                        fields=["article_count"], name="contact_con_article_c4f41d_idx"
                    ),
                    models.Index(
                        fields=["last_published_at"],
                        name="contact_con_last_pu_9a4c99_idx",
                    ),
                ],
            },
        ),
    ]
