# Generated by Django 6.1.1 on 2026-09-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0012_replace_null_strings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email address for this contact",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly_meeting", "Monthly Meeting"),
                    ("quarterly_meeting", "Quarterly Meeting"),
                    ("worship_group", "Worship Group"),
                    ("yearly_meeting", "Yearly Meeting"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Phone number for this contact",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="website",
            field=models.URLField(
                blank=True, default="", help_text="Website URL for this contact"
            ),
        ),
        migrations.AlterField(
            model_name="meetingaddress",
            name="country",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="meetingaddress",
            name="locality",
            field=models.CharField(
                blank=True, default="", help_text="Locality or city", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="meetingaddress",
            name="postal_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Postal code (or zipcode)",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="meetingworshiptime",
            name="worship_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_day_worship", "First day worship"),
                    ("first_day_worship_2nd", "First day worship, 2nd"),
                    ("business_meeting", "Business meeting"),
                    ("other_regular_meeting", "Other regular meeting"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email address for this contact",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Phone number for this contact",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website",
            field=models.URLField(
                blank=True, default="", help_text="Website URL for this contact"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email address for this contact",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="given_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Enter the given name for a person.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Phone number for this contact",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="website",
            field=models.URLField(
                blank=True, default="", help_text="Website URL for this contact"
            ),
        ),
    ]
