# Generated by Django 3.1.1 on 2020-10-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20200930_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
