# Generated by Django 3.1.1 on 2020-10-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_meetingworshiptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingworshiptime',
            name='worship_type',
            field=models.CharField(blank=True, choices=[('first_day_worship', 'First day worship'), ('first_day_worship_2nd', 'First day worship, 2nd'), ('business_meeting', 'Business meeting'), ('other_regular_meeting', 'Other regular meeting')], max_length=255, null=True),
        ),
    ]
