# Generated by Django 3.1.1 on 2020-11-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_auto_20201028_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='civicrm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
