# Generated by Django 3.1.1 on 2020-11-09 08:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_person_civicrm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPresidingClerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('meeting', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='presiding_clerks', to='contact.meeting')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clerk_of', to='contact.person')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
