# Generated by Django 3.1.1 on 2021-01-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_meetingpresidingclerk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingaddress',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingaddress',
            name='locality',
            field=models.CharField(blank=True, help_text='Locality or city.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingaddress',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code (or zipcode).', max_length=16, null=True),
        ),
    ]
