# Generated by Django 3.1.7 on 2021-04-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_auto_20210113_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='drupal_term_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='drupal_term_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='drupal_term_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
