# Generated by Django 3.1.8 on 2021-04-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0021_auto_20210418_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='drupal_term_id',
            new_name='drupal_author_id',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='drupal_term_id',
            new_name='drupal_author_id',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='drupal_term_id',
            new_name='drupal_author_id',
        ),
    ]
