# Generated by Django 3.1.8 on 2021-04-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0022_auto_20210428_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='drupal_library_author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='drupal_library_author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='drupal_library_author_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
