# Generated by Django 3.1.8 on 2021-05-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0023_auto_20210428_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='drupal_full_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='drupal_full_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='drupal_full_name',
        ),
    ]
