# Generated by Django 2.1.3 on 2018-11-02 19:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazineindexpage',
            name='issue_number',
        ),
        migrations.AddField(
            model_name='magazineindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
