# Generated by Django 2.1.7 on 2019-05-05 20:51

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineArticleAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='contact.Contact')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='magazinearticle',
            name='authored_by',
        ),
        migrations.AddField(
            model_name='magazinearticleauthor',
            name='magazine_article',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='magazine.MagazineArticle'),
        ),
    ]
