# Generated by Django 2.1.3 on 2018-11-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('magazine', '0004_magazinearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineissue',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
