# Generated by Django 2.1.3 on 2018-11-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_magazineissue_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
