# Generated by Django 2.1.7 on 2019-05-20 19:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('magazine', '0006_auto_20190512_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineArticleAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='magazinearticle',
            name='authors',
        ),
        migrations.AddField(
            model_name='magazinearticleauthor',
            name='article',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='magazine.MagazineArticle'),
        ),
        migrations.AddField(
            model_name='magazinearticleauthor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles_authored', to='wagtailcore.Page'),
        ),
    ]
