# Generated by Django 2.1.3 on 2018-11-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_magazinearticle_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineissue',
            name='publication_date',
            field=models.DateField(null=True),
        ),
    ]
