# Generated by Django 2.1.3 on 2018-11-12 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_auto_20181112_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazineissuefeaturedarticle',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_articles', to='magazine.MagazineIssue'),
        ),
    ]
