# Generated by Django 2.1.3 on 2018-12-06 18:49

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('magazine', '0015_magazinetagindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinearticle',
            name='authored_by',
            field=modelcluster.fields.ParentalManyToManyField(related_name='articles', to='author.Author'),
        ),
    ]
