# Generated by Django 2.1.7 on 2019-02-16 17:08

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('magazine', '0016_magazinearticle_authored_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinedepartment',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True,
                                                            populate_from=['name']),
        ),
    ]
