# Generated by Django 2.1.3 on 2018-12-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0016_auto_20181202_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='family_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='given_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
