# Generated by Django 2.1.3 on 2018-12-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0017_auto_20181202_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='family_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='given_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
