# Generated by Django 2.1.3 on 2018-12-06 17:03

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0018_auto_20181202_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleauthor',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleauthor',
            name='author',
        ),
        migrations.AddField(
            model_name='magazinearticle',
            name='authored_by',
            field=modelcluster.fields.ParentalManyToManyField(related_name='articles', to='magazine.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='given_name',
            field=models.CharField(default='', help_text='Enter the given name for a person. This can also be used for an organization name.', max_length=255),
        ),
        migrations.DeleteModel(
            name='ArticleAuthor',
        ),
    ]
