# Generated by Django 2.1.7 on 2019-02-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('magazine', '0018_magazinedepartmentindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinearticle',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='articles', to='magazine.MagazineDepartment'),
        ),
    ]
