# Generated by Django 2.1.3 on 2018-12-06 18:04

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0019_auto_20181206_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['given_name', 'family_name']),
        ),
    ]
