# Generated by Django 2.1.7 on 2019-03-20 20:46

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0021_auto_20190220_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinearticle',
            name='authored_by',
            field=modelcluster.fields.ParentalManyToManyField(related_name='articles', to='contact.Contact'),
        ),
    ]
