# Generated by Django 3.1.7 on 2021-02-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitydirectory',
            options={'verbose_name_plural': 'community directories'},
        ),
    ]
