# Generated by Django 3.2.10 on 2021-12-22 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('community', '0002_auto_20210226_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineworship',
            name='hosted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_worship', to='wagtailcore.page'),
        ),
    ]
