# Generated by Django 2.1.7 on 2019-05-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('community', '0007_communityresourceindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypage',
            name='community_resource_index_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
