# Generated by Django 2.1.7 on 2019-05-12 15:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20190512_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypage',
            name='quaker_organizations_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
