# Generated by Django 4.2.1 on 2023-06-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_squashed_0012_alter_communitypage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineworship",
            name="drupal_body_migrated",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onlineworship",
            name="drupal_node_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onlineworship",
            name="drupal_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
