# Generated by Django 4.2.1 on 2023-06-16 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0013_onlineworship_drupal_body_migrated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="onlineworship",
            old_name="drupal_path",
            new_name="drupal_url_path",
        ),
    ]
