# Generated by Django 4.2.1 on 2023-06-16 11:36

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0014_rename_drupal_path_onlineworship_drupal_url_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineworship",
            name="online_worship_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sunday", "Sunday"),
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="onlineworship",
            name="online_worship_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="onlineworship",
            name="online_worship_timezone",
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
    ]
