# Generated by Django 4.2.1 on 2023-06-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0015_onlineworship_online_worship_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineworship",
            name="drupal_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
