# Generated by Django 6.1.1 on 2026-09-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0017_replace_null_strings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onlineworship",
            name="drupal_body_migrated",
        ),
        migrations.RemoveField(
            model_name="onlineworship",
            name="drupal_path",
        ),
        migrations.RemoveField(
            model_name="onlineworship",
            name="drupal_url_path",
        ),
        migrations.AlterField(
            model_name="communitydirectory",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="onlineworship",
            name="online_worship_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sunday", "Sunday"),
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="onlineworship",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
    ]
