# Generated by Django 6.1.1 on 2026-09-30 06:54

import django.core.validators
import re
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_drop_drupal_fields_non_nullable_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 3), ('rich_text', 4), ('image', 5), ('card', 13), ('card_row', 16), ('spacer', 18)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Level 2 (child of level 1)'), ('h3', 'Level 3 (child of level 2)'), ('h4', 'Level 4 (child of level 3)'), ('h5', 'Level 5 (child of level 4)'), ('h6', 'Level 6 (child of level 5)')], 'help_text': 'These different heading levels help to communicate the organization and hierarchy of the content on a page.'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'The text to appear in the heading.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used to link to a specific location within this page. A slug should only contain letters, numbers, underscore (_), or hyphen (-).', 'required': False, 'validators': (django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'),)}), 3: ('wagtail.blocks.StructBlock', [[('heading_level', 0), ('heading_text', 1), ('target_slug', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add a title', 'required': True}), 7: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')], 'help_text': 'Whether to align the image left or right on the block.', 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'required': False}), 11: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('button_text', 10), ('page_link', 11)]], {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('title', 6), ('text', 7), ('image', 8), ('image_align', 9), ('button', 12)]], {}), 14: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 15: ('wagtail.blocks.StructBlock', [[('page', 14), ('text', 10)]], {'label': 'Page'}), 16: ('wagtail.blocks.ListBlock', (15,), {'template': 'blocks/blocks/card_row.html'}), 17: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 1, 'help_text': "The height of this spacer in 'em' values where 1 em is one uppercase M.", 'min_value': 0}), 18: ('wagtail.blocks.StructBlock', [[('height', 17)]], {})}, null=True),
        ),
    ]
