# Generated by Django 2.2.1 on 2019-05-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('magazine', '0007_auto_20190520_1941'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('community', '0026_auto_20190526_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityResource',
        ),
        migrations.DeleteModel(
            name='CommunityResourceIndexPage',
        ),
    ]
