# Generated by Django 4.2.7 on 2023-11-29 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_alter_user_managers_user_first_name_user_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
