"""Django settings for wf_website project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import logging
import os
import sys
from pathlib import Path

import dj_database_url
import sentry_sdk
from django.contrib.messages import constants as messages_constants
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from sentry_sdk.integrations.django import DjangoIntegration

load_dotenv()

# Determine whether we are executing the test suite with Django's test runner.
RUNNING_TESTS = len(sys.argv) > 1 and sys.argv[1] == "test"

# Disable logging while running tests
if RUNNING_TESTS:
    logging.disable(logging.CRITICAL)

default_allowed_hosts = "127.0.0.1,localhost,westernfriend.eu.ngrok.io"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", default_allowed_hosts).split(",")

default_csrf_trusted_origins = "http://127.0.0.1,https://127.0.0.1,http://localhost,https://localhost,https://westernfriend.eu.ngrok.io"

CSRF_TRUSTED_ORIGINS = os.getenv(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default_csrf_trusted_origins,
).split(",")

# Build paths inside the project like this: BASE_DIR / "subdir"
CORE_DIR = Path(__file__).resolve().parent
BASE_DIR = CORE_DIR.parent


SECURE_REFERRER_POLICY = "strict-origin"
# Allow PayPal to open up in-context pop-ups
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() in ("true", "1")

# True only while running `manage.py collectstatic`, which happens at build time
# before runtime secrets exist. See NOT_COLLECTING_STATICFILES further down for
# the long-standing database equivalent — the two are deliberately separate
# expressions, because that one is also False for a bare `manage.py`.
COLLECTING_STATICFILES = len(sys.argv) > 1 and sys.argv[1] == "collectstatic"

if DEBUG:
    SECRET_KEY = "not-so-secret-key"  # noqa: S105 - local development only
else:
    # Fail fast rather than quietly generating one. With a random fallback here,
    # every gunicorn worker started with a DIFFERENT key and nothing reported it:
    # sessions signed by one worker were rejected by the others, so visitors were
    # logged out at random and CSRF checks failed, and password-reset and account
    # activation tokens stopped working on restart. A missing required secret has
    # to stop the process, not degrade the site invisibly.
    SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip()
    if not SECRET_KEY:
        # Stripped, rather than a KeyError on os.environ: an empty or
        # whitespace-only value is just as broken as an absent one, and both are
        # likely ways to get here (an unset variable in a .env or compose file
        # still defines it as ""). A bare KeyError would also accept "   ".
        if COLLECTING_STATICFILES:
            # collectstatic runs during the build, before the runtime secret is
            # injected, and signs nothing — it only walks the static tree. The
            # DATABASES block below already skips its own config for exactly
            # this command; this is the same exemption for the same reason.
            # Deliberately NOT reusing NOT_COLLECTING_STATICFILES: that flag is
            # also False for a bare `manage.py` with no subcommand, which is not
            # the same question being asked here.
            SECRET_KEY = "build-time-placeholder-not-used-to-sign-anything"  # noqa: S105
        else:
            message = (
                "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is off. "
                "Generate one with: python -c 'from django.core.management.utils "
                "import get_random_secret_key; print(get_random_secret_key())'"
            )
            raise ImproperlyConfigured(message)

# Rotation support: Django checks these when a signature fails to verify against
# SECRET_KEY, so the current key can be replaced without logging everyone out or
# invalidating in-flight password-reset tokens. Set the old key here for one
# deploy cycle, then drop it. Same failure this issue is about — sessions dying
# from a key mismatch — just the intentional version.
SECRET_KEY_FALLBACKS = [
    key.strip()
    for key in os.getenv("DJANGO_SECRET_KEY_FALLBACKS", "").split(",")
    if key.strip()
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "debug.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
        },
    },
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "WARNING"),
        },
    },
}

# if SENTRY_DSN is set, then we are running in production
if os.getenv("SENTRY_DSN"):
    # Note: Search view queries are optimized and tagged with "search.queries_optimized=true"
    # If Sentry flags N+1 queries on /search/, check the tag before investigating.
    # Expected query counts are defined in SearchOptimizationTestCase (search/tests.py).
    # Parent pages are bulk-prefetched to avoid N+1 from pageurl tags.
    sentry_sdk.init(
        dsn=os.getenv("SENTRY_DSN"),
        integrations=[DjangoIntegration()],
        traces_sample_rate=1.0,
        profiles_sample_rate=0.3,
    )

# Settings related to DigitalOcean Spaces
# Note: for now, we are using the AWS naming-convention from Boto3
USE_SPACES = os.getenv("DJANGO_USE_SPACES", "False") == "True"
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "sfo3")
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_LOCATION = os.getenv("AWS_LOCATION", "static")
PUBLIC_MEDIA_LOCATION = os.getenv("PUBLIC_MEDIA_LOCATION", "media")
AWS_DEFAULT_ACL = "public-read"
AWS_S3_ENDPOINT_URL = f"https://{AWS_S3_REGION_NAME}.digitaloceanspaces.com"
AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
STATIC_ROOT = BASE_DIR / "static_root"

AUTH_USER_MODEL = "accounts.User"

CART_SESSION_ID = "cart"

# PayPal settings
PAYPAL_CLIENT_ENVIRONMENT = os.getenv("PAYPAL_CLIENT_ENVIRONMENT", "sandbox")
PAYPAL_API_URL = (
    "https://api-m.paypal.com"
    if PAYPAL_CLIENT_ENVIRONMENT.lower() == "production"
    else "https://api-m.sandbox.paypal.com"
)
PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/


# Application definition
INSTALLED_APPS = [
    # First party (apps from this project)
    # keep-sorted start
    "accounts",
    "accounts.apps.CustomUsersAppConfig",
    "addresses",
    "blocks",
    "cart",
    "cli",
    "common",
    "community",
    "contact",
    "documents",
    "events",
    "facets",
    "home",
    "library",
    "magazine",
    "memorials",
    "navigation",
    "news",
    "orders",
    "pagination",
    "payment.apps.PaymentConfig",
    "paypal",
    "search",
    "store",
    "subscription",
    "tags",
    "wf_pages",
    # keep-sorted end
    # Third party (apps that have been installed)
    # keep-sorted start
    "django_browser_reload",
    "django_extensions",
    "modelcluster",
    "storages",
    "taggit",
    "tailwind",
    "wagtail",
    "wagtail.admin",
    "wagtail.contrib.forms",
    "wagtail.contrib.frontend_cache",
    "wagtail.contrib.redirects",
    "wagtail.contrib.routable_page",
    "wagtail.contrib.settings",
    "wagtail.contrib.styleguide",
    "wagtail.documents",
    "wagtail.embeds",
    "wagtail.images",
    "wagtail.search",
    "wagtail.sites",
    "wagtail.snippets",
    "wagtail_color_panel",
    "wagtailmedia",
    # keep-sorted end
    # Contrib (apps that are included in Django)
    # keep-sorted start
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.postgres",
    "django.contrib.sessions",
    "django.contrib.sitemaps",
    "django.contrib.staticfiles",
    # keep-sorted end
    # The theme needs to be listed after tailwind
    # because it uses tailwind's CSS
    "theme",
]

TAILWIND_APP_NAME = "theme"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Must run after the session, CSRF, and message middleware add cookies
    "common.middleware.PublicCacheControlMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    "common.middleware.DiscoveryLinkHeaderMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

X_FRAME_OPTIONS = "SAMEORIGIN"

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [CORE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wagtail.contrib.settings.context_processors.settings",
            ],
            # Enable template debugging for tests and when DEBUG is True
            "debug": DEBUG or RUNNING_TESTS,
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
DATABASE_URL = os.getenv("DATABASE_URL")

NOT_COLLECTING_STATICFILES = len(sys.argv) > 1 and sys.argv[1] != "collectstatic"

if DATABASE_URL:
    DATABASES = {"default": dj_database_url.parse(DATABASE_URL)}
# Default to using local development environment
elif NOT_COLLECTING_STATICFILES:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "wf_website",
            "USER": "postgres",
            "PASSWORD": "postgres",
            "HOST": "localhost",
            "PORT": "5432",
        },
    }


# Cache
# Set DJANGO_CACHE_TABLE in production to share the cache between workers and
# survive restarts. Unset (local development, tests), Django's per-process
# LocMemCache is used. Ceiling: every cache hit is a database query; move to
# django.core.cache.backends.redis.RedisCache if traffic outgrows that.
CACHE_TABLE = os.getenv("DJANGO_CACHE_TABLE")

if CACHE_TABLE:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": CACHE_TABLE,
        },
    }


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    },
}

WAGTAILEMBEDS_FINDERS = [
    {
        "class": "wagtail.embeds.finders.oembed",
    },
]

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_REDIRECT_URL = "/"

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True
WAGTAIL_I18N_ENABLED = True


USE_TZ = True
TIME_ZONE = "America/Los_Angeles"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    CORE_DIR / "static",
]

if USE_SPACES:
    STATIC_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/{AWS_LOCATION}/"

    STORAGES = {
        "default": {
            "BACKEND": "core.storage_backends.MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "core.storage_backends.StaticStorage",
        },
    }

    MEDIA_URL = (
        f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/{PUBLIC_MEDIA_LOCATION}/"
    )

    # Prevent setting URL querystring parameters
    # which are causing 403 errors on DigitalOcean Spaces
    AWS_QUERYSTRING_AUTH = False
else:
    STATIC_URL = "/static/"
    MEDIA_ROOT = BASE_DIR / "media"
    MEDIA_URL = "/media/"


# Wagtail settings
WAGTAIL_SITE_NAME = "Western Friend"

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
BASE_URL = "https://westernfriend.org"

# Registration settings
ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_OPEN = True
REGISTRATION_SALT = "registration"

# Email settings
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "tech@westernfriend.org",
)

email_host = os.getenv("EMAIL_HOST", None)
email_host_user = os.getenv("EMAIL_HOST_USER", None)
email_host_password = os.getenv("EMAIL_HOST_PASSWORD", None)

# If the EMAIL authentication environment variables are set, use SMTP backend
if (
    email_host is not None
    and email_host_user is not None
    and email_host_password is not None
):
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": email_host,
                "port": int(os.getenv("EMAIL_PORT", "587")),
                "username": email_host_user,
                "password": email_host_password,
                "use_tls": os.getenv("EMAIL_USE_TLS", "True") == "True",
                "use_ssl": os.getenv("EMAIL_USE_SSL", "False") == "True",
            },
        },
    }
else:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.console.EmailBackend",
        },
    }

WAGTAILADMIN_BASE_URL = "/admin"

# Edge caching of public pages at Cloudflare.
# See docs/specifications/edge_caching.md.
# Seconds Cloudflare keeps a public page; 0 marks every response private.
PUBLIC_CACHE_EDGE_TTL = int(os.getenv("DJANGO_PUBLIC_CACHE_EDGE_TTL", "0"))
# Seconds browsers keep a public page; short because browsers can't be purged.
PUBLIC_CACHE_BROWSER_TTL = int(os.getenv("DJANGO_PUBLIC_CACHE_BROWSER_TTL", "60"))

# Wagtail purges published and unpublished pages from Cloudflare.
CLOUDFLARE_API_TOKEN = os.getenv("CLOUDFLARE_API_TOKEN")
CLOUDFLARE_ZONE_ID = os.getenv("CLOUDFLARE_ZONE_ID")

if CLOUDFLARE_API_TOKEN and CLOUDFLARE_ZONE_ID:
    WAGTAILFRONTENDCACHE = {
        "cloudflare": {
            "BACKEND": "wagtail.contrib.frontend_cache.backends.CloudflareBackend",
            "BEARER_TOKEN": CLOUDFLARE_API_TOKEN,
            "ZONEID": CLOUDFLARE_ZONE_ID,
        },
    }


INTERNAL_IPS = [
    "127.0.0.1",
]


MESSAGE_TAGS = {
    messages_constants.DEBUG: "alert alert-secondary",
    messages_constants.INFO: "alert alert-info",
    messages_constants.SUCCESS: "alert alert-success",
    messages_constants.WARNING: "alert alert-warning",
    messages_constants.ERROR: "alert alert-danger",
}
