# Generated by Django 2.2.8 on 2019-12-25 18:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('memorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('given_name', models.CharField(default='', help_text='Enter the given name for a person.', max_length=255)),
                ('family_name', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('dates_are_approximate', models.BooleanField()),
                ('memorial_minute', wagtail.core.fields.RichTextField(blank=True)),
                ('memorial_meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memorial_minutes', to='contact.Meeting')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
