# Generated by Django 3.2.2 on 2021-06-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0002_memorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='given_name',
        ),
    ]
