# Generated by Django 6.1.1 on 2026-09-26 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("memorials", "0003_memorial_drupal_body_migrated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memorial",
            name="drupal_body_migrated",
        ),
        migrations.RemoveField(
            model_name="memorial",
            name="drupal_path",
        ),
    ]
