# Generated by Django 3.2.2 on 2021-06-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0026_auto_20210513_0642'),
        ('memorials', '0003_auto_20210624_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='memorial_person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='memorial_minute', to='contact.person'),
            preserve_default=False,
        ),
    ]
