# Generated by Django 3.2.2 on 2021-06-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0005_memorial_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='drupal_memorial_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
