# Generated by Django 3.2.2 on 2021-06-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0006_memorial_drupal_memorial_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='display_name',
        ),
    ]
