# Generated by Django 3.2.2 on 2021-06-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0007_remove_memorial_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='dates_are_approximate',
            field=models.BooleanField(default=False),
        ),
    ]
