# Generated by Django 3.2.2 on 2021-06-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0026_auto_20210513_0642'),
        ('memorials', '0008_alter_memorial_dates_are_approximate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='memorial_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memorial_minutes', to='contact.meeting'),
        ),
    ]
