# Generated by Django 3.2.2 on 2021-06-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0009_alter_memorial_memorial_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
