# Generated by Django 3.1.1 on 2020-12-09 16:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatepage',
            name='suggested_donation_amounts',
            field=wagtail.core.fields.StreamField([('amount', wagtail.core.blocks.IntegerBlock())], blank=True, null=True),
        ),
    ]
