# Generated by Django 3.1.1 on 2020-12-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
