# Generated by Django 3.1.1 on 2020-12-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(default='donor@example.com', help_text='Please enter your email', max_length=254),
            preserve_default=False,
        ),
    ]
