# Generated by Django 3.1.1 on 2020-12-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_donation_donor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_family_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_given_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
