# Generated by Django 3.1.1 on 2021-01-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_auto_20210106_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
