# Generated by Django 3.1.1 on 2021-01-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_donation_donor_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, default='', max_length=255)),
                ('extended_address', models.CharField(blank=True, default='', max_length=255)),
                ('po_box_number', models.CharField(blank=True, default='', help_text='P.O. Box, if relevant.', max_length=32)),
                ('locality', models.CharField(blank=True, help_text='Locality or city.', max_length=255, null=True)),
                ('region', models.CharField(blank=True, default='', help_text='State or region.', max_length=255)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code (or zipcode).', max_length=16, null=True)),
                ('country', models.CharField(blank=True, default='United States', max_length=255, null=True)),
                ('address_type', models.CharField(choices=[('mailing', 'Mailing'), ('worship', 'Worship')], max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
