# Generated by Django 3.1.1 on 2021-01-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_donoraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donations.donoraddress'),
        ),
    ]
