# Generated by Django 3.1.1 on 2021-01-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_donation_donor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donoraddress',
            name='locality',
            field=models.CharField(blank=True, help_text='Locality or city', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donoraddress',
            name='po_box_number',
            field=models.CharField(blank=True, default='', help_text='P.O. Box, if relevant', max_length=32),
        ),
        migrations.AlterField(
            model_name='donoraddress',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code (or zipcode)', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='donoraddress',
            name='region',
            field=models.CharField(blank=True, default='', help_text='State or region', max_length=255),
        ),
    ]
