# Generated by Django 3.1.1 on 2021-01-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_auto_20210113_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
