# Generated by Django 3.1.1 on 2021-01-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_donation_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='braintree_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
