# Generated by Django 3.1.1 on 2021-01-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_donation_braintree_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='braintree_id',
            new_name='braintree_transaction_id',
        ),
    ]
