# Generated by Django 3.1.1 on 2021-02-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_auto_20210127_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('once', 'Once'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='once', max_length=255, null=True),
        ),
    ]
