# Generated by Django 3.1.1 on 2021-02-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_donation_recurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='recurring',
        ),
    ]
