# Generated by Django 3.1.1 on 2021-02-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0017_remove_donation_recurring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatepage',
            old_name='suggested_donation_amounts',
            new_name='suggested_donation_amounts_once',
        ),
    ]
