# Generated by Django 3.1.1 on 2021-02-16 17:21

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_auto_20210216_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatepage',
            name='suggested_donation_amounts_monthly',
            field=wagtail.core.fields.StreamField([('amount', wagtail.core.blocks.IntegerBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='suggested_donation_amounts_yearly',
            field=wagtail.core.fields.StreamField([('amount', wagtail.core.blocks.IntegerBlock())], blank=True, null=True),
        ),
    ]
