# Generated by Django 3.1.1 on 2021-02-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_auto_20210216_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatepage',
            name='suggested_donation_amounts_monthly',
        ),
        migrations.RemoveField(
            model_name='donatepage',
            name='suggested_donation_amounts_yearly',
        ),
    ]
