# Generated by Django 3.1.7 on 2021-02-26 09:20

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0021_auto_20210216_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepage',
            name='suggested_donation_amounts',
            field=wagtail.core.fields.StreamField([('suggested_donation_amounts', wagtail.core.blocks.StructBlock([('once', wagtail.core.blocks.ListBlock(wagtail.core.blocks.IntegerBlock(label='Amount'))), ('monthly', wagtail.core.blocks.ListBlock(wagtail.core.blocks.IntegerBlock(label='Amount'))), ('yearly', wagtail.core.blocks.ListBlock(wagtail.core.blocks.IntegerBlock(label='Amount')))], max_num=1))], blank=True, null=True),
        ),
    ]
