# Generated by Django 2.1.7 on 2019-05-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('given_name', models.CharField(default='', help_text='Enter the given name for a person. This can also be used for an organization name.', max_length=255)),
                ('family_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_type', models.CharField(choices=[('monthly_meeting', 'Monthly Meeting'), ('person', 'Person'), ('quaker_organization', 'Quaker Organization'), ('quarterly_meeting', 'Quarterly Meeting'), ('worship_group', 'Worship Group'), ('yearly_meeting', 'Yearly Meeting')], max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(editable=False, max_length=255, null=True)),
            ],
            options={
                'db_table': 'contact',
            },
            bases=('wagtailcore.page',),
        ),
    ]
