# Generated by Django 2.1.7 on 2019-04-21 22:39

from django.db import migrations, models
import django_extensions.db.fields
import wagtail.search.index


class Migration(migrations.Migration):

    replaces = [('contact', '0001_initial'), ('contact', '0002_contacttype'), ('contact', '0003_contact_contact_type'), ('contact', '0004_auto_20190409_1902'), ('contact', '0005_auto_20190421_2236'), ('contact', '0006_delete_contacttype')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(default='', help_text='Enter the given name for a person. This can also be used for an organization name.', max_length=255)),
                ('family_name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, overwrite=True, populate_from=['given_name', 'family_name'])),
                ('full_name', models.CharField(editable=False, max_length=255, null=True)),
                ('contact_type', models.CharField(choices=[('monthly_meeting', 'Monthly Meeting'), ('person', 'Person'), ('quaker_organization', 'Quaker Organization'), ('worship_group', 'Worship Group'), ('yearly_meeting', 'Yearly Meeting')], default='unknown', max_length=255)),
            ],
            options={
                'db_table': 'contact',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
