# Generated by Django 2.1.7 on 2019-04-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_squashed_0006_delete_contacttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('monthly_meeting', 'Monthly Meeting'), ('person', 'Person'), ('quaker_organization', 'Quaker Organization'), ('quarterly_meeting', 'Quarterly Meeting'), ('worship_group', 'Worship Group'), ('yearly_meeting', 'Yearly Meeting')], max_length=255),
        ),
    ]
