# Generated by Django 2.1.7 on 2019-04-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contacttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.ContactType'),
        ),
    ]
