# Generated by Django 2.1.7 on 2019-05-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('contact', '0003_auto_20190510_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('meeting_type', models.CharField(choices=[('monthly_meeting', 'Monthly Meeting'), ('quarterly_meeting', 'Quarterly Meeting'), ('worship_group', 'Worship Group'), ('yearly_meeting', 'Yearly Meeting')], max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting',
                'ordering': ['title'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['title'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('given_name', models.CharField(default='', help_text='Enter the given name for a person.', max_length=255)),
                ('family_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'person',
                'ordering': ['title'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='given_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
    ]
