# Generated by Django 2.1.7 on 2019-04-09 19:02

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, overwrite=True, populate_from=['given_name', 'family_name']),
        ),
    ]
