# Generated by Django 3.2.8 on 2021-10-13 17:42

from django.db import migrations
import documents.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wf_pages', '0002_alter_wfpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfpage',
            name='body',
            field=wagtail.core.fields.StreamField([('document', documents.blocks.DocumentEmbedBlock()), ('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'superscript', 'superscript', 'strikethrough', 'blockquote'])), ('quote', wagtail.core.blocks.BlockQuoteBlock())]),
        ),
    ]
