# Generated by Django 4.2.1 on 2023-06-12 06:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("wf_pages", "0001_squashed_0016_wfpagetag_wfpage_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="MollyWingateBlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="MollyWingateBlogPage",
            fields=[
                (
                    "wfpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wf_pages.wfpage",
                    ),
                ),
                ("publication_date", models.DateField(verbose_name="Publication date")),
            ],
            options={
                "verbose_name": "Molly Wingate Blog Post",
                "verbose_name_plural": "Molly Wingate Blog Posts",
            },
            bases=("wf_pages.wfpage",),
        ),
        migrations.AddField(
            model_name="wfpage",
            name="drupal_node_id",
            field=models.IntegerField(
                blank=True,
                help_text="Used only for content from old Drupal website.",
                null=True,
            ),
        ),
    ]
