# Generated by Django 6.1.1 on 2026-09-26 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wf_pages", "0022_alter_wfpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wfpage",
            name="body_migrated",
        ),
        migrations.RemoveField(
            model_name="wfpage",
            name="drupal_body_migrated",
        ),
        migrations.RemoveField(
            model_name="wfpage",
            name="drupal_path",
        ),
    ]
