# Generated by Django 4.2.1 on 2023-05-07 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BoardDocument",
            new_name="PublicBoardDocument",
        ),
    ]
