# Generated by Django 4.2.1 on 2023-05-09 18:40

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_publicboarddocumentindexpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicboarddocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("corporation_documents", "Corporation Documents"),
                    ("annual_reports", "Annual Reports"),
                    (
                        "relations_with_monthly_meetings",
                        "Relations with Monthly Meetings",
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="publicboarddocumentindexpage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
