# Generated by Django 4.2.1 on 2023-05-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_meetingdocumentindexpage_meetingdocument"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetingdocument",
            options={"ordering": ["-publication_date"]},
        ),
        migrations.AddIndex(
            model_name="meetingdocument",
            index=models.Index(
                fields=["publication_date"],
                name="documents_m_publica_bebe89_idx",
            ),
        ),
    ]
