# Generated by Django 4.2.1 on 2023-05-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_alter_meetingdocument_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="meetingdocument",
            index=models.Index(
                fields=["document_type"],
                name="documents_m_documen_534774_idx",
            ),
        ),
    ]
