# Generated by Django 4.2.1 on 2023-05-17 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_meetingdocument_documents_m_documen_534774_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetingdocument",
            options={
                "ordering": [
                    "-publication_date",
                    "publishing_meeting",
                    "document_type",
                    "title",
                ],
            },
        ),
    ]
