# Generated by Django 4.2.1 on 2023-06-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0001_squashed_0012_alter_meetingdocument_document_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicboarddocument",
            name="category",
            field=models.CharField(
                choices=[
                    (
                        "corporation_documents_current_year",
                        "Corporation Documents - current year",
                    ),
                    (
                        "corporation_documents_prior_years",
                        "Corporation Documents - prior years",
                    ),
                    ("annual_reports", "Annual Reports"),
                    (
                        "relations_with_monthly_meetings",
                        "Relations with Monthly Meetings",
                    ),
                    ("board_photos", "Board Photos"),
                ],
                max_length=100,
            ),
        ),
    ]
