# Generated by Django 5.0.6 on 2024-09-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0016_alter_meetingdocument_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicboarddocument",
            name="category",
            field=models.CharField(
                choices=[
                    (
                        "corporation_documents_current_year",
                        "Corporation Documents - current year",
                    ),
                    (
                        "corporation_documents_prior_years",
                        "Corporation Documents - prior years",
                    ),
                    ("annual_reports", "Annual Reports"),
                    (
                        "relations_with_monthly_meetings",
                        "Relations with Monthly Meetings",
                    ),
                    ("board_photos", "Board Photos"),
                    ("board_membership_about", "Board Membership - About"),
                ],
                max_length=100,
            ),
        ),
    ]
