# Generated by Django 6.1.1 on 2026-09-26 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0018_alter_meetingdocument_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingdocument",
            name="drupal_body_migrated",
        ),
        migrations.RemoveField(
            model_name="meetingdocument",
            name="drupal_path",
        ),
        migrations.RemoveField(
            model_name="publicboarddocument",
            name="drupal_body_migrated",
        ),
        migrations.RemoveField(
            model_name="publicboarddocument",
            name="drupal_path",
        ),
    ]
