# Generated by Django 4.1.5 on 2023-01-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_meeting_civicrm_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="drupal_author_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="drupal_author_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="drupal_author_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
