# Generated by Django 4.1.5 on 2023-01-29 16:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_alter_meeting_drupal_author_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="drupal_duplicate_author_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="drupal_duplicate_author_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="drupal_duplicate_author_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
