# Generated by Django 4.2.1 on 2023-05-24 06:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    replaces = [
        ("home", "0001_initial"),
        ("home", "0002_initial"),
        ("home", "0003_delete_homepagefeaturedarticle"),
        ("home", "0004_delete_homepagefeaturedevent"),
    ]

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("magazine", "0001_initial"),
        ("wagtailcore", "0066_collection_management_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
