# Generated by Django 3.2.12 on 2022-03-21 08:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("magazine", "0001_initial"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagefeaturedarticle",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="magazine.magazinearticle",
            ),
        ),
        migrations.AddField(
            model_name="homepagefeaturedarticle",
            name="home_page",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_articles",
                to="home.homepage",
            ),
        ),
    ]
