# Generated by Django 3.2.13 on 2022-06-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePageFeaturedArticle",
        ),
    ]
