# Generated by Django 4.1.2 on 2022-10-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_delete_homepagefeaturedarticle"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePageFeaturedEvent",
        ),
    ]
