# Generated by Django 2.2.4 on 2019-11-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, default='', max_length=255)),
                ('postal_code', models.CharField(max_length=16)),
                ('po_box_number', models.CharField(blank=True, default='', max_length=32)),
                ('address_locality', models.CharField(max_length=255)),
                ('address_region', models.CharField(blank=True, default='', max_length=255)),
                ('address_country', models.CharField(default='United States', max_length=255)),
            ],
        ),
    ]
