# Generated by Django 4.1.2 on 2022-10-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_event_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Whether this event should be featured on the home page.",
            ),
        ),
    ]
