# Generated by Django 4.1.6 on 2023-02-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("events", "0014_alter_event_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events_sponsored",
                to="wagtailcore.page",
            ),
        ),
    ]
