# Generated by Django 2.1.7 on 2019-04-21 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('community', '0002_auto_20190419_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlymeetingpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='yearlymeetingpage',
            name='yearly_meeting',
        ),
        migrations.AlterField(
            model_name='communitypageyearlymeeting',
            name='yearly_meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contact.Contact'),
        ),
        migrations.DeleteModel(
            name='YearlyMeetingPage',
        ),
    ]
