# Generated by Django 2.1.7 on 2019-05-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_communitypageyearlymeeting_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypageyearlymeeting',
            name='community_page_instance',
        ),
        migrations.RemoveField(
            model_name='communitypageyearlymeeting',
            name='yearly_meeting',
        ),
        migrations.DeleteModel(
            name='CommunityPageYearlyMeeting',
        ),
    ]
