# Generated by Django 2.1.7 on 2019-05-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_communityresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityresource',
            old_name='intro',
            new_name='description',
        ),
    ]
