# Generated by Django 2.1.7 on 2019-05-12 14:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_communitypage_community_resource_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypage',
            name='community_directory_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='communitypage',
            name='online_worship_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
