# Generated by Django 2.1.7 on 2019-05-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20190512_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypage',
            old_name='community_directory_intro',
            new_name='community_directories_intro',
        ),
    ]
