# Generated by Django 2.1.7 on 2019-05-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_auto_20190526_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypage',
            name='community_directories_intro',
        ),
        migrations.RemoveField(
            model_name='communitypage',
            name='community_resources_index_page',
        ),
        migrations.RemoveField(
            model_name='communitypage',
            name='online_worship_intro',
        ),
        migrations.RemoveField(
            model_name='communitypage',
            name='quaker_organizations_intro',
        ),
    ]
