# Generated by Django 6.0 on 2025-12-09 14:48
# Adds PostgreSQL indexes to wagtailsearch_indexentry table for improved search performance

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # Required for concurrent index creation

    dependencies = [
        ("wagtailsearch", "0006_customise_indexentry"),
    ]

    operations = [
        # Add index on content_type_id for faster JOINs
        migrations.RunSQL(
            sql="""
            CREATE INDEX CONCURRENTLY IF NOT EXISTS
            wagtailsearch_indexentry_content_type_id_idx
            ON wagtailsearch_indexentry (content_type_id);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS wagtailsearch_indexentry_content_type_id_idx;
            """,
        ),
        # Add index on object_id for faster JOINs
        migrations.RunSQL(
            sql="""
            CREATE INDEX CONCURRENTLY IF NOT EXISTS
            wagtailsearch_indexentry_object_id_idx
            ON wagtailsearch_indexentry (object_id);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS wagtailsearch_indexentry_object_id_idx;
            """,
        ),
        # Add GIN index for full-text search on title (already tsvector type)
        migrations.RunSQL(
            sql="""
            CREATE INDEX CONCURRENTLY IF NOT EXISTS
            wagtailsearch_indexentry_title_gin_idx
            ON wagtailsearch_indexentry
            USING GIN (title);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS wagtailsearch_indexentry_title_gin_idx;
            """,
        ),
        # Add GIN index for full-text search on body (already tsvector type)
        migrations.RunSQL(
            sql="""
            CREATE INDEX CONCURRENTLY IF NOT EXISTS
            wagtailsearch_indexentry_body_gin_idx
            ON wagtailsearch_indexentry
            USING GIN (body);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS wagtailsearch_indexentry_body_gin_idx;
            """,
        ),
        # Add composite index for the common JOIN condition
        migrations.RunSQL(
            sql="""
            CREATE INDEX CONCURRENTLY IF NOT EXISTS
            wagtailsearch_indexentry_content_type_object_id_idx
            ON wagtailsearch_indexentry (content_type_id, object_id);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS wagtailsearch_indexentry_content_type_object_id_idx;
            """,
        ),
    ]
