# Generated by Django 4.2.1 on 2023-05-18 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("wf_pages", "0017_mollywingateblogindex"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MollyWingateBlogIndex",
            new_name="MollyWingateBlogIndexPage",
        ),
    ]
