# Generated by Django 4.2.1 on 2023-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wf_pages", "0019_mollywingateblogpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="wfpage",
            name="drupal_node_id",
            field=models.IntegerField(
                blank=True,
                help_text="Used only for content from old Drupal website.",
                null=True,
            ),
        ),
    ]
