# Generated by Django 4.2 on 2023-05-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memorials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memorial",
            options={
                "ordering": (
                    "memorial_person__family_name",
                    "memorial_person__given_name",
                )
            },
        ),
    ]
