# Generated by Django 4.2.5 on 2023-10-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_braintree_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paypal_order_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
