# Generated by Django 2.2.4 on 2019-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190827_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_locality',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
