# Generated by Django 4.2.6 on 2023-10-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_paypal_payment_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["paypal_order_id"], name="orders_orde_paypal__03df56_idx"
            ),
        ),
    ]
