# Generated by Django 4.2.7 on 2023-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_order_orders_orde_paypal__03df56_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="recipient_po_box_number",
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_street_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reicipient street address and/or PO box",
                max_length=255,
            ),
        ),
    ]
