# Generated by Django 5.0.6 on 2024-05-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paypal_transaction_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
