# Generated by Django 2.2.4 on 2019-10-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191020_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='recipient_family_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_given_name',
        ),
        migrations.AddField(
            model_name='order',
            name='purchaser_meeting_or_organization',
            field=models.CharField(blank=True, default='', help_text='Enter the meeting or organization name, if this purchaser is a meeting or organization.', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(default='', help_text='Enter the recipient name (as it should appear on shipping label).', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchaser_family_name',
            field=models.CharField(blank=True, default='', help_text='Enter the family name for the purchaser.', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchaser_given_name',
            field=models.CharField(blank=True, default='', help_text='Enter the given name for the purchaser.', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_address_region',
            field=models.CharField(blank=True, default='', help_text='State for the shipping address.', max_length=255),
        ),
    ]
