# Generated by Django 5.1.7 on 2025-05-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_alter_order_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="recipient_address_country",
            field=models.CharField(
                choices=[("United States", "United States")],
                default="United States",
                help_text="Country for shipping.",
                max_length=255,
            ),
        ),
    ]
