# Generated by Django 5.0.6 on 2024-05-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_alter_order_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paypal_transaction_id",
            field=models.CharField(blank=True, default="", max_length=255, unique=True),
        ),
    ]
