# Generated by Django 2.2.4 on 2019-12-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20191030_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='braintree_id',
            field=models.CharField(blank=True, help_text='DO NOT EDIT. Used to cross-reference orders with Braintree payments.', max_length=255),
        ),
    ]
