# Generated by Django 6.0.2 on 2026-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_alter_order_recipient_address_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the order paid notification email was sent.",
                null=True,
            ),
        ),
    ]
