# Generated by Django 6.0.2 on 2026-02-04 08:57

import logging

from django.db import migrations
from django.utils import timezone

logger = logging.getLogger(__name__)


def backfill_notification_sent_at(apps, schema_editor):
    """
    Backfill notification_sent_at for existing paid orders.

    This prevents existing paid orders from triggering notification emails
    if they are re-saved in the admin.
    """
    Order = apps.get_model("orders", "Order")

    # Update all orders where paid=True and notification_sent_at is None
    paid_orders = Order.objects.filter(paid=True, notification_sent_at__isnull=True)
    count = paid_orders.update(notification_sent_at=timezone.now())

    if count > 0:
        logger.info(
            f"Backfilled notification_sent_at for {count} existing paid order(s)."
        )


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration - no-op.

    We don't clear notification_sent_at timestamps because we cannot
    distinguish between timestamps set by this backfill migration and
    timestamps legitimately created after the migration ran.
    Leaving the timestamps in place is harmless and prevents data loss.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_order_notification_sent_at"),
    ]

    operations = [
        migrations.RunPython(backfill_notification_sent_at, reverse_backfill),
    ]
