# Generated by Django 6.0.2 on 2026-02-04 09:12

import django.contrib.postgres.fields
import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_backfill_notification_sent_at"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookstoreOrderNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=orders.models.get_default_notification_emails,
                        help_text="Email addresses that will receive notifications when bookstore orders are paid. One email per line. Default: editor@westernfriend.org",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bookstore Order Notifications",
            },
        ),
    ]
