# Generated by Django 2.2.4 on 2019-12-04 19:42

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinearticle',
            name='teaser',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
