# Generated by Django 2.2.8 on 2019-12-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('magazine', '0002_magazinearticle_teaser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveIssue',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('internet_archive_identifier', models.CharField(db_index=True, help_text='Identifier for Internet Archive item.', max_length=255, unique=True)),
                ('western_friend_volume', models.CharField(help_text='Related Western Friend volume.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
