# Generated by Django 2.1.7 on 2019-05-05 21:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20190505_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineArticleDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='magazine.MagazineDepartment')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='magazinearticle',
            name='department',
        ),
        migrations.AddField(
            model_name='magazinearticledepartment',
            name='magazine_article',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='magazine.MagazineArticle'),
        ),
    ]
