# Generated by Django 2.1.7 on 2019-05-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20190505_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazinearticledepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='magazinearticledepartment',
            name='magazine_article',
        ),
        migrations.AddField(
            model_name='magazinearticle',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='magazine.MagazineDepartment'),
        ),
        migrations.DeleteModel(
            name='MagazineArticleDepartment',
        ),
    ]
