# Generated by Django 2.2.8 on 2019-12-30 20:15

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_archiveissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('toc_page_number', models.IntegerField(help_text='Enter the page number as it appears in the Table of Contents', verbose_name='Table of Contents page number')),
                ('pdf_page_number', models.IntegerField(help_text='Enter the number of the page in the PDF. This sometimes differs from the table of contents.', verbose_name='PDF page number')),
                ('archive_issue', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_articles', to='magazine.ArchiveIssue')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
