# Generated by Django 2.2.8 on 2019-12-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_archivearticle_archivearticleauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivearticle',
            name='title',
            field=models.CharField(default='Default title', max_length=255),
            preserve_default=False,
        ),
    ]
