# Generated by Django 2.2.8 on 2019-12-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_archivearticle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivearticle',
            name='pdf_page_number',
            field=models.PositiveIntegerField(help_text='Enter the number of the page in the PDF. This sometimes differs from the table of contents.', verbose_name='PDF page #'),
        ),
    ]
