# Generated by Django 2.1.7 on 2019-05-12 11:46

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_auto_20190505_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinearticle',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(related_name='articles', to='contact.Contact'),
        ),
    ]
