# Generated by Django 2.2.9 on 2020-01-14 18:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0009_auto_20200114_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveissue',
            name='table_of_contents',
            field=wagtail.core.fields.StreamField([('Article', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('authors', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock())), ('toc_page_number', wagtail.core.blocks.IntegerBlock()), ('pdf_page_number', wagtail.core.blocks.IntegerBlock())]))], blank=True, null=True),
        ),
    ]
