# Generated by Django 2.2.9 on 2020-01-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0010_archiveissue_table_of_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveissue',
            name='western_friend_volume',
            field=models.CharField(blank=True, help_text='Related Western Friend volume.', max_length=255, null=True),
        ),
    ]
