# Generated by Django 2.2.9 on 2020-01-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0011_auto_20200126_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveissue',
            name='publication_date',
            field=models.DateField(help_text='Please select the first day of the publication month', null=True),
        ),
    ]
