# Generated by Django 2.2.9 on 2020-01-29 17:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0012_archiveissue_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineindexpage',
            name='deep_archive_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
