# Generated by Django 2.2.9 on 2020-02-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0015_magazineindexpage_featured_deep_archive_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinearticle',
            name='body_migrated',
            field=models.TextField(blank=True, help_text='Used only for content from old Drupal website.', null=True),
        ),
    ]
