# Generated by Django 2.2.9 on 2020-02-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0016_magazinearticle_body_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineissue',
            name='issue_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
