# Generated by Django 3.2.2 on 2021-05-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0022_auto_20210513_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveissue',
            name='table_of_contents',
        ),
    ]
