# Generated by Django 3.2.2 on 2021-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0024_archivearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivearticle',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, help_text='Page number as it appears the original document', null=True),
        ),
        migrations.AddField(
            model_name='archivearticle',
            name='pdf_page_number',
            field=models.PositiveIntegerField(blank=True, help_text='Page in the actual PDF file, when it differs from the original document', null=True),
        ),
        migrations.AddField(
            model_name='archivearticle',
            name='title',
            field=models.CharField(default='Default title', max_length=255),
            preserve_default=False,
        ),
    ]
