# Generated by Django 3.2.2 on 2021-05-21 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('magazine', '0025_auto_20210521_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivearticle',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_articles_authored', to='wagtailcore.page'),
        ),
    ]
