# Generated by Django 4.2.1 on 2023-06-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0025_alter_archivearticleauthor_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveissue",
            name="drupal_body_migrated",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="archiveissue",
            name="drupal_node_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="archiveissue",
            name="drupal_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="magazinearticle",
            name="drupal_body_migrated",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="magazinearticle",
            name="drupal_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="magazineissue",
            name="drupal_body_migrated",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="magazineissue",
            name="drupal_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
