# Generated by Django 4.2.3 on 2023-07-16 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0027_alter_magazinearticle_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazineissue",
            name="publication_date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Please select the first day of the publication month",
            ),
        ),
    ]
