# Generated by Django 3.2.2 on 2021-05-26 10:32

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0027_auto_20210521_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivearticle',
            options={},
        ),
        migrations.RemoveField(
            model_name='archivearticle',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='archivearticleauthor',
            name='article',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_authors', to='magazine.archivearticle'),
        ),
    ]
