# Generated by Django 3.2.6 on 2021-08-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0030_archivearticle_drupal_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinearticle',
            name='drupal_node_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
