# Generated by Django 3.2.6 on 2021-08-18 16:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('magazine', '0031_magazinearticle_drupal_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinearticleauthor',
            name='article',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='magazine.magazinearticle'),
        ),
        migrations.AlterField(
            model_name='magazinearticleauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_authored', to='wagtailcore.page'),
        ),
    ]
