# Generated by Django 5.0.3 on 2024-03-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0032_alter_magazinearticle_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivearticle",
            name="pdf_page_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Page in the actual PDF file"
            ),
        ),
        migrations.AlterField(
            model_name="archivearticle",
            name="toc_page_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Page number as it appears the original document"
            ),
        ),
    ]
