# Generated by Django 3.2.6 on 2021-09-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0033_alter_magazinearticle_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinearticle',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this article in the related issue and allow full access without a subscription?'),
        ),
    ]
