# Generated by Django 5.1 on 2024-09-07 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0033_alter_archivearticle_pdf_page_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="magazinearticle",
            options={
                "verbose_name": "Magazine Article",
                "verbose_name_plural": "Magazine Articles",
            },
        ),
        migrations.AlterModelOptions(
            name="magazinearticleauthor",
            options={
                "verbose_name": "Magazine Article Author",
                "verbose_name_plural": "Magazine Article Authors",
            },
        ),
    ]
