# Generated by Django 3.2.6 on 2021-09-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0034_magazinearticle_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MagazineIssueFeaturedArticle',
        ),
    ]
