# Generated by Django 6.0 on 2025-12-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0035_alter_magazinearticle_body"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazineissue",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                help_text="When uploading images,please choose the highest quality available that meets the upload requirements",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
