# Generated by Django 3.2.8 on 2021-10-13 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0036_alter_magazinearticle_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinearticle',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='magazine.magazinedepartment'),
        ),
    ]
