# Generated by Django 6.1.1 on 2026-09-26 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0036_alter_magazineissue_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazineissue",
            name="publication_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Please select the first day of the publication month",
            ),
        ),
    ]
