# Generated by Django 6.1.1 on 2026-09-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0038_replace_null_strings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archiveissue",
            name="drupal_body_migrated",
        ),
        migrations.RemoveField(
            model_name="archiveissue",
            name="drupal_path",
        ),
        migrations.RemoveField(
            model_name="magazinearticle",
            name="body_migrated",
        ),
        migrations.RemoveField(
            model_name="magazinearticle",
            name="drupal_body_migrated",
        ),
        migrations.RemoveField(
            model_name="magazinearticle",
            name="drupal_path",
        ),
        migrations.RemoveField(
            model_name="magazineissue",
            name="drupal_body_migrated",
        ),
        migrations.RemoveField(
            model_name="magazineissue",
            name="drupal_path",
        ),
        migrations.AlterField(
            model_name="archiveissue",
            name="western_friend_volume",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Related Western Friend volume.",
                max_length=255,
            ),
        ),
    ]
