# Generated by Django 6.1.1 on 2026-09-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0039_drop_drupal_fields_non_nullable_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinearticle',
            name='exclude_from_ai',
            field=models.BooleanField(default=False, help_text="Ask AI systems not to use this article for AI answers or AI training, for example at the contributor's request. Readers and search engines can still find it.", verbose_name='Exclude from AI use'),
        ),
    ]
